### ISSUE TITLE
Tab titles are offset to the top

### ISSUE THREAD

**Issue by daelvn** [nokocu/nochrome#1]
For some reason, tab titles do this:

![image](https://github.com/nokocu/nochrome/assets/7452388/6e1688bc-6e76-4c2d-8e6f-483d3a497e38)

It's pretty much a brand new Vivaldi installation on Linux (EndeavorOS). I follwed all the installation steps. I'm willing to give more info if needed.

**Comment by nokocu** [comment]
This issue seems to appear on Linux only, and i previously only tested it on Windows. I already know the fix and will implement it soon in my free time. Thanks for reporting the issue

**Comment by nokocu** [comment]
Fixed in v2 https://github.com/nokocu/nochrome/releases/tag/v2
